apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: default
spec:
  provider:
    vault:
      server: https://vault:4981
      path: secret
      version: v2
      caProvider:
        type: Secret
        name: vault-ca
        key: vault.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: telegraf
          serviceAccountRef:
            name: telegraf
