apiVersion: v1
kind: Service
metadata:
  name: consul-exporter
  labels:
    app: consul-exporter
spec:
  selector:
    app: consul-exporter
  ports:
    - name: metrics
      port: 9107
      targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-exporter
  labels:
    app: consul-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-exporter
  template:
    metadata:
      labels:
        app: consul-exporter
    spec:
      containers:
        - name: consul-exporter
          image: prom/consul-exporter
          args:
            - "--consul.server=consul:8500"
          ports:
            - name: metrics
              containerPort: 9107
