apiVersion: v1
kind: Service
metadata:
  name: mosquitto-exporter
  labels:
    app: mosquitto-exporter
spec:
  selector:
    app: mosquitto-exporter
  ports:
    - name: metrics
      port: 9234
      targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-exporter
  labels:
    app: mosquitto-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto-exporter
  template:
    metadata:
      labels:
        app: mosquitto-exporter
    spec:
      containers:
        - name: mosquitto-exporter
          image: jryberg/mosquitto-exporter:v0.7.7
          ports:
            - name: metrics
              containerPort: 9234
          env:
            - name: BROKER_ENDPOINT
              value: tcp://mosquitto:1883
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  name: telegraf-mqtt
                  key: username
            - name: MQTT_PASS
              valueFrom:
                secretKeyRef:
                  name: telegraf-mqtt
                  key: password
